"""add audit integrity hash chain

Revision ID: 21eca51078a1
Revises: bfb68ce02aaf
Create Date: 2026-03-25 17:41:11.180835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21eca51078a1'
down_revision: Union[str, Sequence[str], None] = 'bfb68ce02aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('entry_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_log', sa.Column('prev_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'prev_hash')
    op.drop_column('audit_log', 'entry_hash')
    # ### end Alembic commands ###
