"""add encrypted api key to projects

Revision ID: 35a9e5cf497f
Revises: 6d8e2fe9c1cb
Create Date: 2026-03-26 14:32:50.082294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a9e5cf497f'
down_revision: Union[str, Sequence[str], None] = '6d8e2fe9c1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('api_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'api_key_encrypted')
    # ### end Alembic commands ###
