"""add advanced permission fields

Revision ID: 644d5118e14f
Revises: 21eca51078a1
Create Date: 2026-03-26 10:31:04.959736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '644d5118e14f'
down_revision: Union[str, Sequence[str], None] = '21eca51078a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission_rules', sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('permission_rules', sa.Column('rate_limit', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('permission_rules', sa.Column('data_level', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('permission_rules', sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission_rules', 'requires_approval')
    op.drop_column('permission_rules', 'data_level')
    op.drop_column('permission_rules', 'rate_limit')
    op.drop_column('permission_rules', 'schedule')
    # ### end Alembic commands ###
