"""add pending approvals and webhooks

Revision ID: 6d8e2fe9c1cb
Revises: 644d5118e14f
Create Date: 2026-03-26 11:36:52.833124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d8e2fe9c1cb'
down_revision: Union[str, Sequence[str], None] = '644d5118e14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('tool', sa.String(length=255), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_approvals_agent_id'), 'pending_approvals', ['agent_id'], unique=False)
    op.create_index(op.f('ix_pending_approvals_project_id'), 'pending_approvals', ['project_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('events', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_project_id'), 'webhooks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_project_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_pending_approvals_project_id'), table_name='pending_approvals')
    op.drop_index(op.f('ix_pending_approvals_agent_id'), table_name='pending_approvals')
    op.drop_table('pending_approvals')
    # ### end Alembic commands ###
