"""initial tables

Revision ID: bfb68ce02aaf
Revises: 
Create Date: 2026-03-25 16:45:17.349693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfb68ce02aaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('delegated_by', sa.String(length=255), nullable=True),
    sa.Column('tool', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('delegation_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_agent_time', 'audit_log', ['agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_agent_id'), 'audit_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_project_id'), 'audit_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_log_tool'), 'audit_log', ['tool'], unique=False)
    op.create_index('ix_audit_project_time', 'audit_log', ['project_id', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=50), server_default='free', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_api_key_hash'), 'projects', ['api_key_hash'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_project_id'), 'agents', ['project_id'], unique=False)
    op.create_table('agent_tokens',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tokens_agent_id'), 'agent_tokens', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tokens_token_hash'), 'agent_tokens', ['token_hash'], unique=True)
    op.create_table('delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('delegated_by_type', sa.String(length=20), nullable=False),
    sa.Column('delegated_by_id', sa.String(length=255), nullable=False),
    sa.Column('permissions_granted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_agent_id'), 'delegations', ['agent_id'], unique=False)
    op.create_table('permission_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('tool_pattern', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_perm_agent_tool', 'permission_rules', ['agent_id', 'tool_pattern'], unique=False)
    op.create_index(op.f('ix_permission_rules_agent_id'), 'permission_rules', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_rules_agent_id'), table_name='permission_rules')
    op.drop_index('ix_perm_agent_tool', table_name='permission_rules')
    op.drop_table('permission_rules')
    op.drop_index(op.f('ix_delegations_agent_id'), table_name='delegations')
    op.drop_table('delegations')
    op.drop_index(op.f('ix_agent_tokens_token_hash'), table_name='agent_tokens')
    op.drop_index(op.f('ix_agent_tokens_agent_id'), table_name='agent_tokens')
    op.drop_table('agent_tokens')
    op.drop_index(op.f('ix_agents_project_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_projects_api_key_hash'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_audit_project_time', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tool'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_project_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_agent_id'), table_name='audit_log')
    op.drop_index('ix_audit_agent_time', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
